### ISSUE TITLE
ZAP now has hooks for customizing scans

### ISSUE THREAD

**Issue by cudandres** [ICTU/zap-baseline#11]
I just wanted to highlight that ZAP baseline scripts now have a hook system to add in your custom functionality instead of having to fork scripts & add your mods.

https://github.com/zaproxy/zaproxy/blob/develop/docker/docs/scan-hooks.md

Here is an example of fully using the hooks to customize scanning against Juice Shop.
https://github.com/rezen/zap-tutorial/blob/master/assets/hooks-goal.py

**Comment by dicksnel** [comment]
Hi, we already had a branch which implemented this. This branch is now merged to the master!
