### ISSUE TITLE
Permission to working directory denied, report generation fails

### ISSUE THREAD

**Issue by n7902** [ICTU/zap-baseline#14]
Noticed that the reports for my scans were not being generated. Ran below command in debug mode and found it is unable to write to the directory. 

**command: docker run --network="host" -v /home/adminngumina:/zap/wrk:rw -t ictu/zap2docker-weekly zap-full-scan.py -t https://mysiteexample.local/ --hook=/zap/auth_hook.py  -z auth.username="Ngumina"  auth.loginurl=https://mysiteexample..local/#/login auth.username_field="username" auth.password_field="password" auth.password="Password" auth.submit_field="loginButton button button-md button-default button-default-md button-md-primary"**

Error

RROR Permission denied 2020-01-23 14:44:03,136 I/O error(13): Permission denied Traceback (most recent call last): File "/zap/zap-full-scan.py", line 444, in main write_report(base_dir + report_json, zap.core.jsonreport()) File "/zap/zap_common.py", line 503, in write_report with open(file_path, mode='wb') as f: IOError: [Errno 13] Permission denied:

**Comment by dicksnel** [comment]
@n7902 does the directory "/home/adminngumina" have RW access?

Can you paste the full log?

**Comment by n7902** [comment]
It does, and just to sanity check, I've tried a few other host directories which I know have RW. 

And sure, are you looking for the full stack trace or for the zap.out logs from within the container?

**Comment by dicksnel** [comment]
Hi @n7902  I can replicate the issue and will make a fix.

**Comment by dicksnel** [comment]
@n7902 can you try running it with the param -u root in the Docker command?

**Comment by n7902** [comment]
yep, that worked! I'll use that for now, thanks very my much

**Comment by snehadominic** [comment]
@n7902 Hi, can you please explain the fix for this issue? What does 'root' in '-u root' means? Is it the root folder. I had tried that and an error is thrown.

**Comment by dicksnel** [comment]
@snehadominic it means the container is started as root user.
