### ISSUE TITLE
-bash: -z: command not found issue

### ISSUE THREAD

**Issue by AbhishekPuranam** [ICTU/zap-baseline#15]
Hi
-Z command not found when I use authenticated scan. Could you kindly fix it.

   docker run --rm -v $(pwd):/zap/wrk/:rw -t ictu/zap2docker-weekly zap-baseline.py \
  -t http://hackazon.webscantest.com/user/login \
  -r testreport.html \
   --hook=/zap/auth_hook.py \ 
  -z "auth.loginurl=http://hackazon.webscantest.com/user/login \
      auth.auto
      auth.username="****" \
      auth.password="******" \
      auth.auto=1
      auth.submit_field="loginbtn" \
      auth.exclude=".*logout.*,\Qhttp://url.com/logout\E.*""

FAIL-NEW: 0	FAIL-INPROG: 0	WARN-NEW: 10	WARN-INPROG: 0	INFO: 0	IGNORE: 0	PASS: 41
OpenJDK 64-Bit Server VM warning: Exception java.lang.OutOfMemoryError occurred dispatching signal SIGHUP to handler- the VM may need to be forcibly terminated
$   -z "auth.loginurl=http://hackazon.webscantest.com/user/login \
>       auth.auto
>       auth.username="******" \
>       auth.password="*****" \
>       auth.auto=1
>       auth.submit_field="loginbtn" \
>       auth.exclude=".*logout.*,\Qhttp://url.com/logout\E.*""
-bash: -z: command not found

**Comment by fniessink** [comment]
The error message you got from bash indicates that you put the -z argument on a separate line. 

This works for me:

    $ docker run --rm -v $(pwd):/zap/wrk/:rw -t ictu/zap2docker-weekly zap-baseline.py -t http://hackazon.webscantest.com/user/login -r testreport.html --hook=/zap/auth_hook.py -z "auth.loginurl=http://hackazon.webscantest.com/user/login
    auth.auto
    auth.username=''
    auth.password='*'
    auth.auto=1
    auth.submit_field='loginbtn'
    auth.exclude='.logout.,\Qhttp://url.com/logout\E.'"

Does that help?

**Comment by AbhishekPuranam** [comment]
Thanks the error was resolved. Instead of the script creating the context everytime, can we invoke the context saved in volumes.
INFO: Created user preferences directory.
Setup a new context for target http://hackazon.webscantest.com/account
