### ISSUE TITLE
Need capability to fetch authentication from the .context than generating.

### ISSUE THREAD

**Issue by AbhishekPuranam** [ICTU/zap-baseline#17]
Using ZAP GUI, the user can generate the context to mention if it's a form-based login or JSON based login. With the location provided in the volumes, the scanner should be able to fetch. 
https://nullsweep.com/dynamic-security-scanning-in-a-ci-zap-scanning-with-jenkins/

**Comment by dicksnel** [comment]
@AbhishekPuranam I don't understand your question, can you provide more info?

This tool does not rely on the built-in support for Form based login, but uses a Webdriver to submit forms.
