### ISSUE TITLE
Unable to find certaint html components

### ISSUE THREAD

**Issue by Yvtq8K3n** [ICTU/zap-baseline#25]
I was trying to test this on a Traditional Web Application (bodgeit) that uses form-based login.
![image](https://user-images.githubusercontent.com/19397871/96594239-4eddce00-12e2-11eb-88cb-a6c5cf05a5c1.png)

However due to the validation you currently using: type == "text", 
![image](https://user-images.githubusercontent.com/19397871/96595550-b1839980-12e3-11eb-8675-2c120a8a83ac.png)

It is unable to find the input with the id=username
![image](https://user-images.githubusercontent.com/19397871/96595841-00313380-12e4-11eb-8de2-27b55b7b2482.png)

**Comment by dicksnel** [comment]
@Yvtq8K3n I will change the script to type is text or type is empty.

In the mean time, you can ofcourse specify your own Xpath using the auth.username_field parameter, for example //input[id='username']

**Comment by dicksnel** [comment]
Fixed in a5ae4363264647bd3115d53c05b7b82b51b92c5d
