### ISSUE TITLE
zap_auth doesn't support logins with username with type=email

### ISSUE THREAD

**Issue by iTaybb** [ICTU/zap-baseline#31]
Assuming html login form username is actually an email, this control:

`<input name="email" placeholder="Email" type="email" class="form-control">`

won't be identified, even when run with `auth.username_field="email"`

It would seem that this happens as the code in zap_auth.py explicitly looks for `@type='text' or not(@type)` controls.

**Comment by dicksnel** [comment]
@iTaybb I just made a commit which includes username fields with type=email. Can you pull the latest image and try again?

**Comment by iTaybb** [comment]
It seems that with the latest image, the code crashes:
` Traceback (most recent call last):
   File "/zap/zap_auth.py", line 77, in login
     self.auto_login(config)
   File "/zap/zap_auth.py", line 163, in auto_login
     self.submit_form(username_element)
   File "/zap/zap_auth.py", line 169, in submit_form
     if self.config.auth_submitaction == "click":
 AttributeError: 'ZapAuth' object has no attribute 'config'`

**Comment by dicksnel** [comment]
@iTaybb oops... fixed the bug. Can you try again?

**Comment by iTaybb** [comment]
Looks great! 10x
