### ISSUE TITLE
Consider submiting a PR to zaproxy

### ISSUE THREAD

**Issue by psiinon** [ICTU/zap-baseline#5]
Is the authentication working well for you?
If so how about submitting a PR back to https://github.com/zaproxy/zaproxy ?
That way your work will help more people and you wont have to keep applying your changes every time we update our scripts.

**Comment by remoteadmin** [comment]
Hi Simon,

Yes, the authentication works fine for us. I will cleanup this repo and make a PR to the zaproxy repo in the coming weeks.

**Comment by tumluliu** [comment]
HI @remoteadmin , may I ask if you are still preparing for submitting a PR to zaproxy? I am asking because we are so requiring this great auth options feature in your custom scripts. If the PR is gonna happen soon, we may wait and deploy the next version of zaproxy with auth. Otherwise, we will switch from zaproxy to here. Thanks!

**Comment by remoteadmin** [comment]
Hi Simon,

We did some cleanup and refactoring to use the new hook mechanism. You can see the result in this [feature branch](https://github.com/ICTU/zap-baseline/tree/Rebase-From-Fork). If you are satisfied with the solution we are happy to do a PR. 

Please let us know.

**Comment by dhartford** [comment]
Hi Team,
Would it be possible to attempt another engagement on this?  As an end-user trying to find a means for more automated (CLI) zap usage w/ authentication, I like the methods proposed here.

Reviewing https://github.com/zaproxy/zaproxy/issues/4105 and the PR's associated with it and their current delayed/blocked state for several months (associated with a GSOC which may have ended), I would like to see the great work done here pulled into zaproxy.

**Comment by fniessink** [comment]
I'll discuss with @dicksnel next week and see what we can do.

**Comment by dicksnel** [comment]
The new hook mechanism of zap-baseline.py from OWASP will be used, so a PR is no longer needed.
